apiVersion: v1
kind: Pod
metadata:
  labels:
    app: frontend
    run: frontend
  name: frontend
spec:
  containers:
  - image: 172.31.15.193:5000/myvel123/flask:1
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
