apiVersion: extensions/v1beta1
kind: deployment
metadata:
  labels:
    app: frontend
    run: frontend
  name: frontend
spec:
  containers:
  - image: 172.31.15.193:5000/myvel123/flask:2
    name: frontend
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
